[package]
name = "babble"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.11.1"
clap = { version = "4.0.18", features = ["derive"] }
comrak = "0.15.0"
itertools = "0.10.5"
